### PR TITLE
feat: Support custom waiting time for keepalived to create files

### PR DESCRIPTION
**Pull request by mingqing**
Signed-off-by: mingqing <limingqing@cyou-inc.com>

to fix: #75

### CODE REVIEW

**Comment by mehdy** [comment]
@mingqing Thanks for opening the PR and I'm sorry for the long delay.
I think it wouldn't be a good idea to create a custom wait-time option to handle this issue. Instead, I suggest a fixed waiting time (e.g. 6s).
It would be much better to check for the files' existence and wait for 1s and check again, then 2s and then 3. (A total of 6s).

Please let me know if you'd like to make the changes.

**Comment by mingqing** [comment]
@mehdy I tried to check if the file is generated and set the max waiting time to 6s as a timeout (or others fix time), then compare and resubmit the PR.

**Comment by mehdy** [comment]
@mingqing Hi there, Didn't you want to do this feature?

**Comment by mingqing** [comment]
@mehdy I testing new code. sync the latest code on github when resolving conflicts it closed the this PR, i will retry open it.

**Pull request closed without merging**
