### PR TITLE
feat: add excluded vip support

### PR DESCRIPTION
**Pull request by dmachard**
This PR add a new metric `keepalived_vrrp_excluded_state` to follow excluded Virtual IPs as described in https://keepalived.readthedocs.io/en/latest/configuration_synopsis.html#vrrp-instance-definitions-synopsis

keepalived.data example:

```
------< VRRP Topology >------
 VRRP Instance = VI_IPV4
   VRRP Version = 2
   State = MASTER
   ....
   Virtual IP :
     10.0.0.2 dev ens224 scope global set
   Virtual IP Excluded :
     10.0.0.3 dev ens224 scope global set
   ...
```

### CODE REVIEW

**Comment by dmachard** [comment]
Any chance to have a review on it ?

**Review by clwluvw — CHANGES_REQUESTED** [review]
Can you please add a test case?

**Comment by dmachard** [comment]
new testcases added, ready for review

**Review by clwluvw — CHANGES_REQUESTED** [review]
Can you please just add the `Virtual IP Excluded` to the 2.2.7 test file? They have the same style - It's kinda useless introducing a new test file for that.

**Comment by dmachard** [comment]
done

**Review by clwluvw — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
